### PR TITLE
Feature/add bat scripts for windows platform

### PR DESCRIPTION
**Pull request by vojkog**
Add windows (`.bat`) scripts for Docker Compose operations

Copy existing `.sh` scripts to `.bat` variant.

### CODE REVIEW

**Comment by francav** [comment]
Hey @vojkog. Thanks very much for this. What to you think about moving all these docker-compose files to a folder? Maybe with linux and windows subfolders?

**Review by francav — CHANGES_REQUESTED** [review]
Hey @vojkog. Thanks very much for this. What to you think about moving all these docker-compose files to a folder? Maybe with linux and windows subfolders?

**Comment by francav** [comment]
> Hey @vojkog. Thanks very much for this. What to you think about moving all these docker-compose files to a folder? Maybe with linux and windows subfolders?

Also, what's the difference between linux and windows files?

**Comment by vojkog** [comment]
Thank you, @francav, for your response. 

I see your point; there is a bit of clutter in the project's root, especially with added Windows scripts. 

As you have probably seen, there are no substantial differences between `.sh` and `.bat` files, but Windows doesn't natively understand or execute `.sh˙` files.

Maybe we can leave docker files as-is and move only `scripts` into a single `scripts` dir or in the platform-specific sub dirs, e.g.:
```
/project-root
|-- /scripts
|   |-- /linux
|   |   |-- docker-full-startup.sh
|   |   |-- ....
|   |-- /windows
|   |   |-- docker-full-startup.bat
|   |   |-- ....
...
|-- README.md
```
This change will require updating documentation also.

**Comment by francav** [comment]
That would be great @vojkog Would you like to help with that?

**Review by francav — APPROVED** [review]

**Comment by francav** [comment]
Hey @vojkog  thank you very much for that work!

**Pull request merged**
